document.addEventListener("DOMContentLoaded",()=>{
  const nav=document.querySelector("#import-nav"),view=document.querySelector("#resume-import"),file=document.querySelector("#resume-file"),drop=document.querySelector("#resume-drop"),stages=[...document.querySelectorAll(".import-stage")],steps=[...document.querySelectorAll(".import-steps div")];
  function toast(message){const t=document.querySelector("#toast");t.textContent=message;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2100)}
  function showStage(id,index){stages.forEach(x=>x.classList.toggle("active",x.id===id));steps.forEach((x,i)=>{x.classList.toggle("active",i===index);x.classList.toggle("done",i<index)})}
  nav.addEventListener("click",()=>{document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));view.classList.add("active");nav.classList.add("active");document.querySelector("#crumb").textContent="IMPORT";document.querySelector("#title").textContent="Bring in an existing resume";window.scrollTo({top:0,behavior:"smooth"})});
  document.querySelector("#choose-resume").addEventListener("click",()=>file.click());["dragenter","dragover"].forEach(name=>drop.addEventListener(name,event=>{event.preventDefault();drop.classList.add("dragging")}));["dragleave","drop"].forEach(name=>drop.addEventListener(name,event=>{event.preventDefault();drop.classList.remove("dragging")}));drop.addEventListener("drop",event=>{if(event.dataTransfer.files.length)processFile(event.dataTransfer.files[0])});file.addEventListener("change",()=>{if(file.files.length)processFile(file.files[0])});
  const resumeLink=document.createElement("div");resumeLink.className="resume-link-import";resumeLink.innerHTML='<span>OR IMPORT FROM A LINK</span><div><input id="resume-link" type="url" placeholder="https://example.com/resume.pdf"><button id="import-resume-link">Import link</button></div><small>Use a direct link to a Markdown, text, PDF, Word, or PowerPoint document.</small>';drop.insertAdjacentElement("afterend",resumeLink);
  document.querySelector("#import-resume-link").addEventListener("click",()=>{const url=document.querySelector("#resume-link").value.trim();if(!/^https?:\/\//i.test(url)){toast("Enter a valid http or https document link");return}const clean=url.split(/[?#]/)[0],name=decodeURIComponent(clean.split("/").pop()||"linked-resume");processLinkedFile(name,url)});
  document.querySelectorAll(".import-choice input").forEach(input=>input.addEventListener("change",()=>{document.querySelectorAll(".import-choice").forEach(x=>x.classList.remove("selected"));input.closest(".import-choice").classList.add("selected")}));
  function processFile(chosen){const allowed=/\.(md|markdown|txt|pdf|doc|docx|ppt|pptx)$/i;if(!allowed.test(chosen.name)){toast("Choose a Markdown, text, PDF, Word, or PowerPoint file");return}document.querySelector("#processing-file").textContent=chosen.name;document.querySelector("#review-file-name").textContent=chosen.name+" · ready to import";showStage("import-stage-processing",1);setTimeout(()=>document.querySelector("#process-text").classList.add("done"),500);setTimeout(()=>document.querySelector("#process-sections").classList.add("done"),900);setTimeout(()=>document.querySelector("#process-content").classList.add("done"),1300);setTimeout(()=>showStage("import-stage-review",2),1650)}
  function processLinkedFile(name,url){document.querySelector("#processing-file").textContent=name+" · linked document";document.querySelector("#review-file-name").textContent=name+" · imported from link";showStage("import-stage-processing",1);toast("Fetching document from "+new URL(url).hostname);setTimeout(()=>document.querySelector("#process-text").classList.add("done"),500);setTimeout(()=>document.querySelector("#process-sections").classList.add("done"),900);setTimeout(()=>document.querySelector("#process-content").classList.add("done"),1300);setTimeout(()=>showStage("import-stage-review",2),1650)}
  document.querySelector("#replace-file").addEventListener("click",()=>showStage("import-stage-file",0));document.querySelector("#cancel-import").addEventListener("click",()=>showStage("import-stage-file",0));document.querySelector("#complete-import").addEventListener("click",()=>toast("Resume imported successfully (prototype only)"));
});
