document.addEventListener("DOMContentLoaded",()=>{
  const nav=document.querySelector("#details-nav"),view=document.querySelector("#personal-details"),list=document.querySelector("#profile-list");
  function toast(message){const t=document.querySelector("#toast");t.textContent=message;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2100)}
  nav.addEventListener("click",()=>{document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));view.classList.add("active");nav.classList.add("active");document.querySelector("#crumb").textContent="PROFILE";document.querySelector("#title").textContent="Personal and contact details";window.scrollTo({top:0,behavior:"smooth"})});
  document.querySelector(".photo-button").addEventListener("click",event=>{event.stopPropagation();document.querySelector('nav [data-go="assets"]').click()});
  function updatePreview(){const value=name=>document.querySelector(`[data-preview="${name}"]`).value;["first","last","headline","email","phone"].forEach(name=>document.querySelector("#preview-"+name).textContent=value(name));const mode=document.querySelector('[name="address-display"]:checked').value;document.querySelector("#preview-location").closest("p").hidden=mode==="hide";document.querySelector("#preview-location").textContent=mode==="full"?"123 King St, "+value("city")+", "+value("region")+", "+value("country"):value("city")+", "+value("country")}
  document.querySelectorAll(".preview-field,[name='address-display']").forEach(input=>input.addEventListener("input",updatePreview));
  function wireRemove(button){button.addEventListener("click",()=>button.closest(".profile-row").remove())}document.querySelectorAll(".remove-profile").forEach(wireRemove);
  document.querySelector("#add-profile").addEventListener("click",()=>{const row=document.createElement("div");row.className="profile-row";row.innerHTML='<span class="profile-logo website">⌾</span><select><option>Website</option><option>LinkedIn</option><option>GitHub</option><option>GitLab</option><option>Medium</option><option>Instagram</option></select><input class="social-url" placeholder="Profile URL or username"><label class="show-toggle"><input type="checkbox" checked><i></i></label><button class="remove-profile">×</button>';list.appendChild(row);wireRemove(row.querySelector(".remove-profile"));row.querySelector("input.social-url").focus()});
  document.querySelector("#save-details").addEventListener("click",()=>toast("Personal details saved (prototype only)"));
  if(new URLSearchParams(window.location.search).get("view")==="personal-details")nav.click();
});
