document.addEventListener("DOMContentLoaded",()=>{
  document.querySelector('[data-go="assets"]').addEventListener("click",event=>{event.stopPropagation();document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));document.querySelector("#assets").classList.add("active");event.currentTarget.classList.add("active");document.querySelector("#crumb").textContent="ASSET LIBRARY";document.querySelector("#title").textContent="Your visual identity";window.scrollTo({top:0,behavior:"smooth"})});
  const personalAssets=document.querySelector("#personal-assets"),brandCard=document.createElement("button");brandCard.className="asset-card";brandCard.dataset.kind="logo";brandCard.dataset.name="CV Studio logo";brandCard.innerHTML='<span class="asset-preview brand-asset"><img src="/assets/branding/cv-studio-logo.png" alt="CV Studio logo"></span><b>CV Studio logo</b><small>PNG · Brand asset</small>';personalAssets.insertBefore(brandCard,document.querySelector("#drop-asset"));
  const cards=[...document.querySelectorAll(".asset-card[data-kind]")],detail=document.querySelector("#inspector-detail"),empty=document.querySelector("#inspector-empty");
  function toast(message){const t=document.querySelector("#toast");t.textContent=message;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2100)}
  cards.forEach(card=>card.addEventListener("click",()=>{cards.forEach(x=>x.classList.remove("selected"));card.classList.add("selected");empty.style.display="none";detail.classList.add("open");document.querySelector("#inspector-name").textContent=card.dataset.name;const source=card.querySelector(".asset-preview"),preview=document.querySelector("#inspector-preview");preview.className=source.className;preview.innerHTML=source.innerHTML}));
  const filters=[...document.querySelectorAll("[data-asset-filter]")],search=document.querySelector("#asset-search");function filter(){const kind=document.querySelector("[data-asset-filter].active").dataset.assetFilter,term=search.value.toLowerCase();cards.forEach(card=>card.hidden=!((kind==="all"||card.dataset.kind===kind)&&card.dataset.name.toLowerCase().includes(term)))}filters.forEach(button=>button.addEventListener("click",()=>{filters.forEach(x=>x.classList.remove("active"));button.classList.add("active");filter()}));search.addEventListener("input",filter);
  const modal=document.querySelector("#asset-modal");function openModal(){modal.classList.add("open")}document.querySelector("#upload-trigger").addEventListener("click",openModal);document.querySelector("#drop-asset").addEventListener("click",openModal);document.querySelector("#close-asset-modal").addEventListener("click",()=>modal.classList.remove("open"));modal.addEventListener("click",event=>{if(event.target===modal)modal.classList.remove("open")});
  const sourceTabs=[...document.querySelectorAll("[data-source]")];sourceTabs.forEach(button=>button.addEventListener("click",()=>{sourceTabs.forEach(x=>x.classList.remove("active"));button.classList.add("active");document.querySelectorAll(".source-panel").forEach(x=>x.classList.remove("active"));document.querySelector("#source-"+button.dataset.source).classList.add("active")}));
  const file=document.querySelector(".drop-zone input");document.querySelector(".drop-zone button").addEventListener("click",()=>file.click());file.addEventListener("change",()=>{if(file.files.length){modal.classList.remove("open");toast(file.files[0].name+" added (prototype only)")}});document.querySelector("#import-url").addEventListener("click",()=>{if(!document.querySelector("#asset-url").value.trim()){toast("Enter an image URL first");return}modal.classList.remove("open");toast("Image imported (prototype only)")});document.querySelector("#use-asset").addEventListener("click",()=>toast(document.querySelector("#inspector-name").textContent+" added to the CV"));
});
